name: code_writer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
dependencies:
  dart_style: ^2.3.6
